PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?relation ?option ?headEntities (COUNT(DISTINCT ?h) AS ?headEntitiesForOption) ((COUNT(DISTINCT ?h) / xsd:float(?headEntities)) AS ?optionRepresented) WHERE {
  {
    SELECT ?relation (COUNT(DISTINCT ?head) AS ?headEntities) WHERE { ?head ?relation ?tail . } GROUP BY ?relation
  }
  
  ?h ?relation ?option.
}
GROUP BY ?relation ?option ?headEntities
HAVING ((COUNT(DISTINCT ?h) / xsd:float(?headEntities)) > 0.5)