# Here degree refers to the number of different relation types an entity is conneceted to (head or tail)
SELECT ?entity (COUNT(*) AS ?degree) WHERE {
  GRAPH <http://www.ontotext.com/explicit> {
        { SELECT distinct ?entity ?p1 WHERE {?entity ?p1 ?o1.} }
    UNION
    {
      { SELECT distinct ?entity ?p1 WHERE {?s2 ?p1 ?entity.} }
      FILTER(?s2 != ?entity)
    }
  }
}
GROUP BY ?entity
ORDER BY DESC (?degree)