# What is the combined degree of every entity (in + out degree)
SELECT ?entity (COUNT(*) AS ?degree) WHERE {
  GRAPH <http://www.ontotext.com/explicit> {
    { ?entity ?p1 ?o1. }
    UNION
    {
      ?s2 ?p2 ?entity.
      FILTER(?s2 != ?entity)
    }
  }
}
GROUP BY ?entity
ORDER BY DESC (?degree)