# What relations have an overrepresented tail? (>50% of all tail mentions for a relation)
SELECT ?relation ?tail (COUNT(*) AS ?filteredTripleCount) ?tripleCount (xsd:float((COUNT(*)) / (xsd:float(?tripleCount))) AS ?representation) WHERE {
  GRAPH <http://bias.org/training-graph> {
    {
      SELECT ?relation (COUNT(*) AS ?tripleCount) WHERE { ?s ?relation ?o. }
      GROUP BY ?relation
    }
    ?head ?relation ?tail.
  }
}
GROUP BY ?relation ?tail ?tripleCount
HAVING (((COUNT(*)) / (xsd:float(?tripleCount))) > "0.5"^^xsd:decimal)
ORDER BY DESC (?filteredTripleCount)