PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?relation ?tail (COUNT(*) AS ?filteredTripleCount) ?tripleCount (xsd:float((COUNT(*)) / (xsd:float(?tripleCount))) AS ?representation) WHERE {
  {
    SELECT ?relation (COUNT(*) AS ?tripleCount) WHERE { ?s ?relation ?o. }
    GROUP BY ?relation
  }
  ?head ?relation ?tail.
}
GROUP BY ?relation ?tail ?tripleCount
HAVING (((COUNT(*)) / (xsd:float(?tripleCount))) > "0.5"^^xsd:decimal)
ORDER BY DESC (?filteredTripleCount)