# What are near symmetrical relations in the training graph?
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?relation ?tripleCount ((COUNT(*)) / (xsd:float(?tripleCount)) AS ?symmetryScore) WHERE {
  GRAPH <http://bias.org/training-graph> {
    {
      SELECT ?relation (COUNT(*) AS ?tripleCount) WHERE { ?head ?relation ?tail. }
      GROUP BY ?relation
    }
    ?h ?relation ?t .
    ?t ?relation ?h .
  }
}
GROUP BY ?relation ?tripleCount
HAVING((COUNT(*)) / (xsd:float(?tripleCount)) > 0.75)
ORDER BY DESC(?symmetryScore)